files:
  - source: /core/Piranha.Manager.Localization/Resources/*.resx
    ignore:
      - '*[.]*.resx'
    translation: >-
      /core/Piranha.Manager.Localization/Resources/%file_name%.%two_letters_code%.%file_extension%
